name: Publish Docker Image

on:
  schedule:
    - cron: "0 0 1 * *"
  push:
    paths:
      - 'cuda/**'
      - '.github/workflows/docker-publish.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Replace placeholders
      run: |
        sed -i 's|\$USER\$|${{ secrets.USER }}|g' cuda/Dockerfile
        sed -i 's|\$\$PASSWD_HASH\$\$|${{ secrets.PASSWD_HASH }}|g' cuda/Dockerfile

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: cuda
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/arch-cuda:latest
